// Code generated by fabrica codegen init. DO NOT EDIT.
package resources

import (
	"fmt"
		"os"
		"path/filepath"
		"strings"

	"github.com/openchami/fabrica/pkg/codegen"
	"github.com/example/inventory-v3/pkg/resources/device"
	"github.com/example/inventory-v3/pkg/resources/discoverysnapshot"
)

// RegisterAllResources registers all discovered resources with the generator.
// This file is auto-generated. Re-run 'fabrica codegen init' after adding resources.
func RegisterAllResources(gen *codegen.Generator) error {
	if err := gen.RegisterResource(&device.Device{}); err != nil {
		return fmt.Errorf("failed to register Device: %w", err)
	}
	// Set per-resource tags based on source markers
	if hasVersioningMarker("Device") {
		gen.SetResourceTag("Device", "versioning", "enabled")
	}
	if err := gen.RegisterResource(&discoverysnapshot.DiscoverySnapshot{}); err != nil {
		return fmt.Errorf("failed to register DiscoverySnapshot: %w", err)
	}
	// Set per-resource tags based on source markers
	if hasVersioningMarker("DiscoverySnapshot") {
		gen.SetResourceTag("DiscoverySnapshot", "versioning", "enabled")
	}

	return nil
}

	// hasVersioningMarker inspects the resource source file for the versioning marker comment.
	func hasVersioningMarker(resourceName string) bool {
		// Derive path: pkg/resources/<lower(resourceName)>/<lower(resourceName)>.go
		pkg := strings.ToLower(resourceName)
		path := filepath.Join("pkg", "resources", pkg, pkg+".go")
		data, err := os.ReadFile(path)
		if err != nil {
			return false
		}
		content := string(data)
		return strings.Contains(content, "+fabrica:resource-versioning=enabled")
	}
