// Code generated by Fabrica dev. DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2025-11-17T12:46:44-08:00
//
// # Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for Device resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /devices (list all devices)
//   - GET /devices/{uid} (get specific Device)
//   - POST /devices (create new Device)
//   - PUT /devices/{uid} (update Device spec)
//   - PATCH /devices/{uid} (patch Device spec)
//   - DELETE /devices/{uid} (delete Device)
//   - PUT /devices/{uid}/status (update Device status)
//   - PATCH /devices/{uid}/status (patch Device status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadDevice*/SaveDevice*/DeleteDevice*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Create v2beta1 package: pkg/resources/device/v2beta1/
//  2. Implement converter: v2beta1/converter.go
//  3. Add version-aware storage: storage.LoadDeviceWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/example/inventory-v3/internal/storage"
	"github.com/example/inventory-v3/pkg/resources/device"
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"
)

// GetDevices returns all Device resources
func GetDevices(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	devices, err := storage.LoadAllDevices(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load devices: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, devices)
}

// GetDevice returns a specific Device resource by UID
func GetDevice(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Device UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadDevice() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	device, err := storage.LoadDevice(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Device not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, device)
}

// CreateDevice creates a new Device resource
func CreateDevice(w http.ResponseWriter, r *http.Request) {
	var req CreateDeviceRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Get version context from request
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("Device")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	device := &device.Device{
		Resource: resource.Resource{
			APIVersion:    versionCtx.GroupVersion,
			Kind:          "Device",
			SchemaVersion: versionCtx.ServeVersion,
		},
		Spec: req.DeviceSpec,
	}

	device.Metadata.Initialize(req.Name, uid)

	// Set timestamps
	now := time.Now()
	device.Metadata.CreatedAt = now
	device.Metadata.UpdatedAt = now

	// Set labels and annotations
	for k, v := range req.Labels {
		device.SetLabel(k, v)
	}
	for k, v := range req.Annotations {
		device.SetAnnotation(k, v)
	}

	// Layer 2: Fabrica struct tag validation
	if err := validation.ValidateResource(device); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Layer 3: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), device); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveDevice(r.Context(), device); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save Device: %w", err))
		return
	}

	// Publish resource created event
	if err := events.PublishResourceCreated(r.Context(), "Device", device.GetUID(), device.GetName(), device); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for Device %s: %v\n", device.GetUID(), err)
	}

	respondJSON(w, http.StatusCreated, device)
}

// UpdateDevice updates the spec of an existing Device resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //devices/{uid}/status to update status.
func UpdateDevice(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Device UID is required"))
		return
	}

	device, err := storage.LoadDevice(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Device not found: %w", err))
		return
	}

	var req UpdateDeviceRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates
	if req.Name != "" {
		device.SetName(req.Name)
	}

	// Update spec fields ONLY - status should use /status subresource
	device.Spec = req.DeviceSpec

	// Update labels and annotations
	for k, v := range req.Labels {
		device.SetLabel(k, v)
	}
	for k, v := range req.Annotations {
		device.SetAnnotation(k, v)
	}

	device.Touch()

	if err := storage.SaveDevice(r.Context(), device); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save Device: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": device.Metadata.UpdatedAt,
	}
	if err := events.PublishResourceUpdated(r.Context(), "Device", device.GetUID(), device.GetName(), device, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for Device %s: %v\n", device.GetUID(), err)
	}

	respondJSON(w, http.StatusOK, device)
}

// PatchDevice patches an existing Device resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchDevice(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Device UID is required"))
		return
	}

	device, err := storage.LoadDevice(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Device not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(device.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &device.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata
	device.Touch()

	// Save the patched resource
	if err := storage.SaveDevice(r.Context(), device); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched Device: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": device.Metadata.UpdatedAt,
	}
	if err := events.PublishResourcePatched(r.Context(), "Device", device.GetUID(), device.GetName(), device, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for Device %s: %v\n", device.GetUID(), err)
	}

	respondJSON(w, http.StatusOK, device)
}

// UpdateDeviceStatus updates only the status of a Device resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateDeviceStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Device UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadDevice(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Device not found: %w", err))
		return
	}

	var statusUpdate device.DeviceStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate
	res.Touch()

	if err := storage.SaveDevice(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save Device status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}
	if err := events.PublishResourceUpdated(r.Context(), "Device", res.GetUID(), res.GetName(), res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for Device %s: %v\n", res.GetUID(), err)
	}

	respondJSON(w, http.StatusOK, res)
}

// PatchDeviceStatus patches only the status of a Device resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchDeviceStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Device UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadDevice(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Device not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Touch()

	if err := storage.SaveDevice(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched Device status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}
	if err := events.PublishResourcePatched(r.Context(), "Device", res.GetUID(), res.GetName(), res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for Device %s: %v\n", res.GetUID(), err)
	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteDevice deletes a Device resource
func DeleteDevice(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Device UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	device, err := storage.LoadDevice(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Device not found: %w", err))
		return
	}

	if err := storage.DeleteDevice(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete Device: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}
	if err := events.PublishResourceDeleted(r.Context(), "Device", device.GetUID(), device.GetName(), deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for Device %s: %v\n", device.GetUID(), err)
	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "Device deleted successfully",
		UID:     uid,
	})
}
